name: Build Electron App

on:
  push:
    branches:
      - main  # Ganti dengan branch yang sesuai jika kamu menggunakan branch lain
  pull_request:
    branches:
      - main  # Trigger saat ada pull request yang di-merge ke branch main

jobs:
  build:
    runs-on: windows-latest  # Kamu bisa gunakan ubuntu atau windows-latest, tergantung kebutuhan

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Checkout source code

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Ganti dengan versi Node.js yang kamu gunakan

    - name: Install dependencies
      run: npm install  # Install semua dependencies yang ada di package.json

    - name: Build Electron App
      run: npm run build  # Jalankan perintah build (electron-builder)

    - name: Upload .exe build as artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-exe
        path: dist/**/*    # Menyimpan semua file yang ada di dalam folder dist, tempat output build
